name: Practice Express
on:
  push:
    branches: [main, production]
jobs:
  tests:
    name: 'JDVNHS WebAPI CI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run Test
        run: yarn test
